const accessedCoinsNames = {
  bitcoin: "BTC",
  ethereum: "ETH",
  binancecoin: "BNB",
  dogecoin: "DOGE",
  ripple: "XRP",
  tether: "USDT",
  "usd coin": "USDC",
  cardano: "ADA",
  solana: "SOL",
  polkadot: "DOT",
  litecoin: "LTC",
  "bitcoin cash": "BCH",
  chainlink: "LINK",
  polygon: "MATIC",
  stellar: "XLM",
  cosmos: "ATOM",
  filecoin: "FIL",
  tron: "TRX",
  "ethereum classic": "ETC",
  monero: "XMR",
  eos: "EOS",
  tezos: "XTZ",
  aave: "AAVE",
  maker: "MKR",
  algorand: "ALGO",
  vechain: "VET",
  theta: "THETA",
  avalanche: "AVAX",
  fantom: "FTM",
  hedera: "HBAR",
  neo: "NEO",
  sushi: "SUSHI",
  compound: "COMP",
  dash: "DASH",
  zcash: "ZEC",
  yearnfinance: "YFI",
  synthetix: "SNX",
  celsius: "CEL",
  chiliz: "CHZ",
  thorchain: "RUNE",
  "basic attention token": "BAT",
  waves: "WAVES",
  enjin: "ENJ",
  zilliqa: "ZIL",
  ontology: "ONT",
  qtum: "QTUM",
  omg: "OMG",
  holo: "HOT",
  icon: "ICX",
  bittorrent: "BTT",
  digibyte: "DGB",
  siacoin: "SC",
  horizen: "ZEN",
  kusama: "KSM",
  "1inch": "1INCH",
  ankr: "ANKR",
  curve: "CRV",
  "the graph": "GRT",
  kava: "KAVA",
  loopring: "LRC",
  decentraland: "MANA",
  ocean: "OCEAN",
  ren: "REN",
  sandbox: "SAND",
  storj: "STORJ",
  uma: "UMA",
  "0x": "ZRX",
};

const shortCoinNames = {
  btc: "bitcoin",
  eth: "ethereum",
  bnb: "binancecoin",
  doge: "dogecoin",
  xrp: "ripple",
  usdt: "tether",
  usdc: "usd coin",
  ada: "cardano",
  sol: "solana",
  dot: "polkadot",
  ltc: "litecoin",
  bch: "bitcoin cash",
  link: "chainlink",
  matic: "polygon",
  xlm: "stellar",
  atom: "cosmos",
  fil: "filecoin",
  trx: "tron",
  etc: "ethereum classic",
  xmr: "monero",
  eos: "eos",
  xtz: "tezos",
  aave: "aave",
  mkr: "maker",
  algo: "algorand",
  vet: "vechain",
  theta: "theta",
  avax: "avalanche",
  ftm: "fantom",
  hbar: "hedera",
  neo: "neo",
  sushi: "sushiswap",
  comp: "compound",
  dash: "dash",
  zec: "zcash",
  yfi: "yearnfinance",
  snx: "synthetix",
  cel: "celsius",
  chz: "chiliz",
  rune: "thorchain",
  bat: "basic attention token",
  waves: "waves",
  enjin: "enjin",
  zil: "zilliqa",
  ont: "ontology",
  qtum: "qtum",
  omg: "omg",
  hot: "holo",
  icx: "icon",
  btt: "bittorrent",
  dgb: "digibyte",
  sc: "siacoin",
  zen: "horizen",
  ksm: "kusama",
  "1inch": "1inch",
  ankr: "ankr",
  crv: "curve",
  grt: "the graph",
  kava: "kava",
  lrc: "loopring",
  mana: "decentraland",
  ocean: "ocean",
  ren: "ren",
  sand: "sandbox",
  storj: "storj",
  uma: "uma",
  zrx: "0x",
};

module.exports = { shortCoinNames, accessedCoinsNames };
